### ISSUE TITLE
IcingHackz, do this plz

### ISSUE THREAD

**Issue by iop3** [anonymt-dev/Ping-me#3]
Say *hello* to prove that u are alive. xD

**Comment by IcingHackz** [comment]
a few minutes later...nothing... :O

**Comment by IcingHackz** [comment]
a hour later....nothing..... :0

**Comment by IcingHackz** [comment]
5 hours later....nothing.... :O

**Comment by IcingHackz** [comment]
hmmmmmmmmmmmmmmmmmm

**Comment by RayhanADev** [comment]
5 Days Later...

**Comment by IcingHackz** [comment]
12 days later...

**Comment by RayhanADev** [comment]
well, this is hilarious ngl

**Comment by RayhanADev** [comment]
@theiocoder !!!

**Comment by IcingHackz** [comment]
xD

**Comment by theiocoder** [comment]
god,

**Comment by theiocoder** [comment]
sorry!

**Comment by theiocoder** [comment]
Also, don't close these issues, I will ~~and only I will~~, since it's one of the only ways I can see your comments.
